baseURL: https://antoine-alexandre.com/
languageCode: en-us
title: Antoine-Alexandre Andr√©
theme: yourfolio
disableKinds: [RSS, taxonomy, taxonomyTerm]
googleAnalytics: UA-XXXXX-Y

# Menu items
menu:
  main:
  - name: About me
    weight: 1
    url: /about
  - name: Contact me
    weight: 2
    url: /contact 


# Custom params
params:
  env: development
  logoImage: img/logo.png
  logoImageAlt: Yourfolio Theme brand logo
